apiVersion: v1
kind: Service
metadata:
  name: meetmon
  namespace: {{ NAMESPACE }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    name: meetmon
