swagger: "2.0"
info:
  description: "A cloud endpoint for our application"
  title: "{{ ENDPOINT_NAME }}"
  version: "0.1"
host: "{{ ENDPOINT_NAME }}"
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: query
paths:
  /doWork:
    get:
      operationId: doWork
      description: Fakes some processing.
      responses:
        200:
          description: Successful response
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            type: string
  /doFail:
    get:
      operationId: doFail
      description: Will always fail
      responses:
        200:
          description: Successful response
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            type: string
  /doSecret:
    get:
      operationId: doSecret
      description: Will always fail
      security:
      - api_key: []
      responses:
        200:
          description: Successful response
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            type: string
